In [1]:
# dependecies
import os
import os.path 
import pandas as pd
import re

In [18]:
# creating a list containing all folder names of the dataset
folders = ["business","entertainment","politics","sport","tech"]

In [15]:
# Changing the current working dirctory to the dataset directory

os.chdir("/kaggle/input/bbc-full-text-document-classification/bbc")

In [16]:
# Verifying whether the current directory changed to the desier directory or not
print(os.getcwd())

/kaggle/input/bbc-full-text-document-classification/bbc

In [19]:
# generating  a list call paths containg all the detailed paths for accessing the folders of the dataset 
paths = []
for i in folders:
    paths.append(os.getcwd()+'/'+i)

In [20]:
# printing the path just for verification
print(paths)

['/kaggle/input/bbc-full-text-document-classification/bbc/business', '/kaggle/input/bbc-full-text-document-classification/bbc/entertainment', '/kaggle/input/bbc-full-text-document-classification/bbc/politics', '/kaggle/input/bbc-full-text-document-classification/bbc/sport', '/kaggle/input/bbc-full-text-document-classification/bbc/tech']

In [25]:
# creating two list texts and labels to store the detailed content and
# and the category of the news
texts = []
labels = []

In [26]:
# getting the path of a folders one by one from the list called paths[]
for path in paths:
#     getting filenames one by one from the list of all files under a directory called path
    for filename in os.listdir(path):
#         opening the file in read only mode with encoding latin1
        with open(path+"/"+filename,"r", encoding = "latin") as file:
#             after reading the file contents are stored in a variable called data
            data = file.read()
#             after removing all newline characters and carriage return from the  data,
#             it is being added at the end of the list texts
            data = data.replace("\n"," ").replace('\r','')
            texts.append(data)
            file.close() # file is being closed
#         setting the category of the news as the folder name in which it reside  
        labels.append(os.path.basename(path)) # from the whole path basename only returns the folder name

In [27]:
# creating a pandas dataframe from two lists texts and labels as two columns
df = pd.DataFrame({'texts':texts,'labels':labels})

In [28]:
# Printing the data frame for verification purpose
df

                                                  texts    labels
0     Vodafone appoints new Japan boss  Vodafone has...  business
1     Booming markets shed few tears  The market, fo...  business
2     US regulator to rule on pain drug  US food and...  business
3     Asia quake increases poverty risk  Nearly two ...  business
4     Crude oil prices back above $50  Cold weather ...  business
...                                                 ...       ...
2220  A question of trust and technology  A major go...      tech
2221  Half-Life 2 sweeps Bafta awards  PC first pers...      tech
2222  Doors open at biggest gadget fair  Thousands o...      tech
2223  2D Metal Slug offers retro fun  Like some dril...      tech
2224  Rivals of the Â£400 Apple...  The Mac mini is ...      tech

[2225 rows x 2 columns]

In [29]:
# adding dependencies to encode the categories of the news  with integer
from sklearn.preprocessing import LabelEncoder

In [30]:
# Encoding the categories of the news  with integer
df["labels_to_category"] = LabelEncoder().fit_transform(df["labels"])
# verfing by printing last 11 data from the dataframe
df.tail(11)

,texts,labels,labels_to_category
2214,Peer-to-peer nets 'here to stay' Peer-to-peer...,tech,4
2215,Apple laptop is 'greatest gadget' The Apple P...,tech,4
2216,Concern over RFID tags Consumers are very con...,tech,4
2217,IBM frees 500 software patents Computer giant...,tech,4
2218,Cebit fever takes over Hanover Thousands of p...,tech,4
2219,Local net TV takes off in Austria An Austrian...,tech,4
2220,A question of trust and technology A major go...,tech,4
2221,Half-Life 2 sweeps Bafta awards PC first pers...,tech,4
2222,Doors open at biggest gadget fair Thousands o...,tech,4
2223,2D Metal Slug offers retro fun Like some dril...,tech,4
2224,Rivals of the Â£400 Apple... The Mac mini is ...,tech,4

In [ ]:
# Converting the dataframe into csv file
df.to_csv('/kaggle/working/BBC_news.csv')

In [ ]:
# Verifing whether the csv file is generated properly or not by reading data from it
df2 = pd.read_csv('/kaggle/working/BBC_news.csv', encoding = "latin")
df2